Rails Blog App: Add forms
kkolade/rails_blog_app pull request #7
Opened 2023-07-22 13:20 UTC by kkolade

# In this PR, I:

- Create a method called current_user in the ApplicationController to make current user data available to all controllers.
- Create forms to perform the following functions:
   - Creates a Post on behalf of the current_user (using the method I created in the ApplicationController).
   - Create a comment on behalf of the current_user (using the method created in the ApplicationController).
- Allow Users to add likes to Posts.

2023-07-22 17:59 UTC, laiifuu requested changes
## Hi @kkolade :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://github.com/kkolade/rails_blog_app/assets/93520178/5cee525f-0a69-4f6b-af44-d03d9fe3f078)


## Highlights
- [x] Green linters check :heavy_check_mark: 
- [x] Descriptive PR summary :heavy_check_mark: 

## Required Changes ♻️
- [x] When I tried accessing the page for a single user when that user had no posts, I got the following error: 
![image](https://github.com/kkolade/rails_blog_app/assets/93520178/f9381f96-61b9-409b-8868-9e0816f8222f)
Kindly fix this issue.

_Check the comments under the review. :point_down:_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-22 17:59 UTC, laiifuu commented on app/views/posts/show.html.erb
> +      </div>
Good work adding a form for the user to add a comment :+1: However this form is supposed to be in a the `views/comments/new.html.erb` file.

2023-07-22 17:59 UTC, laiifuu commented on app/controllers/likes_controller.rb
> +    end
After creating a post, I tried adding a like, and it didn't work, the likes counter didn't update. I accessed the list of likes from the rails consoleto make sure, and it was empty: 
![image](https://github.com/kkolade/rails_blog_app/assets/93520178/6c470c3e-7e1c-41e8-9604-aaf261a2e455)
Kindly fix this issue.

2023-07-22 18:27 UTC, kkolade commented
Hi @laiifuu please are you available for a chat on slack

2023-07-24 23:03 UTC, Felix45 requested changes
Hi @kkolade, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: 

You have submitted a project, that was not approved in the previous week. I would like to suggest that you close this PR `without` merging it, then create a new PR and use the new PR to request a review again.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-07-24 23:06 UTC, closed without merging